    GLAZED_DONUTS = "GLAZED DONUTS"
        if GLAZED_DONUTS:
            print(GLAZED_DONUTS)
        else:
  GLAZED_DONUTS = "GLAZED DONUTS"   
            GLAZED_DONUTS = "GLAZED DONUTS"
  for _ in range(10):
      GLAZED_DONUTS = "GLAZED DONUTS"
          GLAZED_DONUTS = "GLAZED DONUTS"
    GLAZED_DONUTS = "GLAZED DONUTS"
          GLAZED_DONUTS = "GLAZED DONUTS"
    if GLAZED_DONUTS == "GLAZED DONUTS":
              GLAZED_DONUTS = "GLAZED DONUTS"
  else:
              GLAZED_DONUTS = "GLAZED DONUTS"
print(GLAZED_DONUTS)
